Distribution analysis
konstantgr/jupyter-duplicates-analysis pull request #1
Opened 2023-01-22 10:32 UTC by konstantgr

Added final version of clone analysis

2023-01-24 13:12 UTC, TitovS commented
General comments:
- test poetry one more time -- I had some problems, but poetry update helped. 
- please, hash scripts names
- typing is important, please add it
- Let's not keep in repo archives or add functionalty to unpack it.

2023-01-24 13:58 UTC, TitovS requested changes

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +    def _get_json_files(folder, max_num):
is it same max_num as in class? Why is it static? Same for folder

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +        return [folder / Path(pos_json) for pos_json in os.listdir(folder) if
We are switching to pathlib because of its superiority. Please use Path.iterdir()

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +                for k, folder in self.in_path.items()}
I didn't get the idea -- what the functionality of this piece?

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +        scripts_files = None if not self.scripts_folder else self._get_json_files(self.scripts_folder, self.max_num)
May be we can make both variable None if there is no folder + check with error if both are none?

2023-01-24 13:58 UTC, TitovS commented on utils/processing_utils.py
> +def filter_clones(
Why this method is in utils. It is definitely part of experiment.

2023-01-24 13:58 UTC, TitovS commented on utils/processing_utils.py
> +    with open(filepath, 'r') as f:
Please use Pathlib functionality. See path.open for details.

2023-01-24 13:58 UTC, TitovS commented on utils/processing_utils.py
> +            except (json.decoder.JSONDecodeError, TypeError):
Please better naming

2023-01-24 13:58 UTC, TitovS commented on utils/processing_utils.py
> +                continue
Never use try-except construction without any type of logging. Add print() at least.

2023-01-24 13:58 UTC, TitovS commented on utils/processing_utils.py
> +def is_break(start: int, finish: int, source: str) -> bool:
it is also part of experiment. For example, sep should be class constant.

2023-01-24 13:58 UTC, TitovS commented on utils/processing_utils.py
> +def get_stats(lst: List, norm: int = 1) -> Dict:
Why not stat util?

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +                for k, folder in self.in_path.items()}
Finally, got it. Let's discuss it on call -- we should redo this.

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +                ]
While i really appreciate list comprehensions, this is too complicated -- lest refactor this to the start loop

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +            try:
Please, decrease size of this try construction. There are only a few lines where KeyError is possible.

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +                continue
At least add print()

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +                stats.append(pd.DataFrame(stats_tmp))
Redundant constructor?

2023-01-24 13:58 UTC, TitovS commented on experiment.py
> +        return ax
and this could be extracted to the utils.

2023-01-24 13:58 UTC, TitovS commented on utils/data_utils.py
> +            continue
log errors!

2023-01-24 16:22 UTC, konstantgr commented on experiment.py
> +        return [folder / Path(pos_json) for pos_json in os.listdir(folder) if
Ok. Will use rglob

2023-01-25 12:34 UTC, konstantgr commented on experiment.py
> +    def _get_json_files(folder, max_num):
done

2023-01-25 12:34 UTC, konstantgr commented on experiment.py
> +        return [folder / Path(pos_json) for pos_json in os.listdir(folder) if
done

2023-01-25 12:35 UTC, konstantgr commented on utils/processing_utils.py
> +def filter_clones(
done

2023-01-25 12:35 UTC, konstantgr commented on experiment.py
> +            try:
done

2023-01-25 12:35 UTC, konstantgr commented on experiment.py
> +                continue
done

2023-01-25 12:35 UTC, konstantgr commented on experiment.py
> +        return ax
deleted

2023-01-25 12:35 UTC, konstantgr commented on utils/data_utils.py
> +            continue
done

2023-04-01 09:29 UTC, merged